# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Check code formatting with Prettier
      - name: Check Code Formatting
        run: npx prettier --check .

      # Step 5: Lint the code with ESLint
      - name: Run ESLint
        run: npx eslint . --ext .ts

      # Step 6: Build the project
      - name: Build
        run: npm run build

      # Step 7: Run tests with coverage
      - name: Run Tests
        run: npm run test -- --coverage

      # Step 8: Validate Commit Messages (Conventional Commits)
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: commitlint.config.ts
